from typing import Protocol


class BrowserPort(Protocol):
    def launch(self) -> None: ...

    def goto(self, url: str) -> None: ...

    def title(self) -> str: ...

    def wait(self, seconds: float) -> None: ...

    def scroll_selector(self, selector: str, pixels: int) -> None: ...

    def query_all_hrefs(self, selector: str) -> list[str]: ...

    def query_text(self, selector: str) -> str | None: ...

    def query_attr(self, selector: str, attribute: str) -> str | None: ...

    def query_text_xpath(self, xpath: str) -> str | None: ...

    def query_attr_xpath(self, xpath: str, attribute: str) -> str | None: ...

    def close(self) -> None: ...
